(bili.live): Optimized GiftMessage and NewGuardMessage
vNerve/vNerveTransmitter pull request #2
Opened 2020-05-31 05:51 UTC by darkflame0

修改了一下 GiftMessage和NewGuardMessage

GiftMessage加上了数量（num）把gift_single_coin改为price，因为total_coin存在打折的情况，并不能准确计算出礼物的数量

NewGuardMessage补充了更多信息，包括数量、购买类型（开通、续费），周期（目前有周舰长和月舰长）

数据来源为USER_TOAST_MSG，该数据样例：
{
"cmd": "USER_TOAST_MSG",
"data": {
"num": 2,
"uid": 23523656,
"unit": "月",
"price": 316000,\总价
"is_show": 0,
"op_type": 2,\1为开通，2为续费
"end_time": 1588305442,
"username": "迷咕咕",
"role_name": "舰长",
"toast_msg": "<%迷咕咕%>续费了主播的舰长",
"user_show": true,
"start_time": 1588305442,
"anchor_show": true,
"guard_level": 3
}
}

2020-05-31 06:12 UTC, cqjjjzr requested changes

2020-05-31 06:12 UTC, cqjjjzr commented on vNerve/bilibili/live/user_message.proto
> +  uint32 num=6;
此处Formatting有点问题

2020-05-31 06:12 UTC, cqjjjzr commented on vNerve/bilibili/live/user_message.proto
> +  GuardBuyType buy_type=5;
Formatting

2020-05-31 06:12 UTC, cqjjjzr commented on vNerve/bilibili/live/user_message.proto
> +enum GuardUnit {
有无比Unit更好的词

2020-05-31 06:13 UTC, cqjjjzr commented on vNerve/bilibili/live/user_message.proto
> +  uint32 num=6;
另外price容易被误解为以人民币为单位，如果是瓜子数量应明确标成coin

2020-05-31 06:23 UTC, darkflame0 commented on vNerve/bilibili/live/user_message.proto
> +  uint32 num=6;
那就用price_coin？

2020-05-31 06:29 UTC, darkflame0 commented on vNerve/bilibili/live/user_message.proto
> +enum GuardUnit {
> 有无比Unit更好的词

这个就暂时没什么头绪了

2020-05-31 06:34 UTC, cqjjjzr commented on vNerve/bilibili/live/user_message.proto
> +  uint32 num=6;
total_coin如何

2020-05-31 06:39 UTC, darkflame0 commented on vNerve/bilibili/live/user_message.proto
> +  uint32 num=6;
> total_coin如何

total_coin是总价值，在用了，price_coin是单价（未打折），sc那边用的也是这个

2020-05-31 09:10 UTC, cqjjjzr commented on vNerve/bilibili/live/user_message.proto
> +  uint32 num=6;
那考虑`gift_single_coin_raw`

2020-06-06 12:38 UTC, H4M5TER commented on vNerve/bilibili/live/user_message.proto
> +enum GuardUnit {
Duration

2020-06-06 12:38 UTC, H4M5TER commented on vNerve/bilibili/live/user_message.proto
> +  uint32 num=6;
sc的proto中pricecoin并不是单价 而是总瓜子数 由原始数据的price*rate计算而来
如果需要说明是未打折的原始加个 我支持加个raw后缀

2020-06-06 12:43 UTC, H4M5TER commented on vNerve/bilibili/live/user_message.proto
> +  GuardBuyType buy_type=5;
推荐使用vscode-proto3插件

2020-06-06 18:15 UTC, darkflame0 commented on vNerve/bilibili/live/user_message.proto
> +  uint32 num=6;
@H4M5TER 我说的就是瓜子数啊，只是SC不存在打折也不存在一次多个的情况，所以单价就等于总瓜子数 词义上也是符合的

2020-06-07 09:45 UTC, H4M5TER commented on vNerve/bilibili/live/user_message.proto
> +  GuardBuyType buy_type = 5;
建议改为`bool isNew = 5;`
如果确实有缺省需要，建议改成
```
oneof foo = {
  bool isNew = 5;
}
```

2020-06-07 09:49 UTC, H4M5TER commented on vNerve/bilibili/live/user_message.proto
> +  GuardBuyType buy_type = 5;
茶栗的建议：
1. 不需要缺省 默认设为新会员
2. 改成isRenew方便理解

2020-06-07 09:51 UTC, H4M5TER commented on vNerve/bilibili/live/user_message.proto
> +  uint32 num=6;
我认为price_coin并没有说明没有打折 只是SC不存在打折而已 如果要在这里用这个词最好还是加个raw

2020-06-07 09:52 UTC, cqjjjzr commented on vNerve/bilibili/live/user_message.proto
> +  uint32 num=6;
https://github.com/darkflame0/vNerveTransmitter/pull/1

2020-06-07 09:53 UTC, H4M5TER commented on vNerve/bilibili/live/user_message.proto
> +  uint32 num=6;
考虑在qq群沟通吗 即时性比较好

2020-06-07 09:57 UTC, H4M5TER commented on vNerve/bilibili/live/user_message.proto
> +enum GuardUnit {
茶栗的建议：

2020-06-08 02:44 UTC, darkflame0 commented on vNerve/bilibili/live/user_message.proto
> +  GuardBuyType buy_type = 5;
我也感觉改成isRenew比较好，这个应该不会有第三个操作了

2020-06-08 02:58 UTC, darkflame0 commented on vNerve/bilibili/live/user_message.proto
> +  uint32 num=6;
> 如何命名其实没那么重要，但是问题在于我们之前的时候并没有考虑打折的情况，如果需要考虑打折的情况，我们需要有哪几个field分别存储什么值呢？

按B站的做法是，price是原单价，num是数量，total_coin是实际总价
舰长系列和SC是后面做的，USER_TOAST_MSG里price就是实际总价
SC的price是人民币价格
这就看命名是不是要统一一下了

2020-06-08 03:03 UTC, darkflame0 commented on vNerve/bilibili/live/user_message.proto
> +  uint32 num=6;
> sc的proto中pricecoin并不是单价 而是总瓜子数 由原始数据的price*rate计算而来
> 如果需要说明是未打折的原始价格 我支持加个raw后缀

我觉得加个raw有点丑。。我推荐用price_coin表示原价 num(count?)表示数量，total_coin表示实际总价，按这个词义single_price_coin感觉没啥用，有总价和数量应该就能算了，而且不加这个前缀默认为single也是符合直觉的

2020-07-07 15:12 UTC, merged